container:
  image: sitapati/docker-alpine-python-node:latest

test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  build_script: yarn compile
  test_script: yarn test
