container:
  image: nikolaik/python-nodejs:python3.5-nodejs14-alpine

test_task:
  pnpm_cache:
    folder: /usr/local/lib/node_modules/pnpm
    populate_script: npm i -g pnpm
    fingerprint_script: npm show pnpm version
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat pnpm-lock.yaml
    populate_script: pnpm i
  build_script: pnpm compile
  test_script: pnpm test
