tasks:
  install:
    image: node:carbon
    command:
      - yarn
    args:
      - install
  test:
    image: node:carbon
    command:
      - yarn
    args:
      - test
  build:
    image: node:carbon
    command:
      - yarn
    args:
      - compile
workflow:
  - install
  - sail:parallel:
      - build
      - test
