name: Node.js CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.9.3
      - name: Retrieve content-addressable store from cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.pnpm-store/v3
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: pnpm i
      - run: pnpm build
      - run: pnpm test
        env:
          CI: true
